language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r req_tests.txt
  - pip install -r req_docs.txt

script:
  - py.test
  - make html

after_success:
  - codecov
