language: python
python: "3.7"
dist: "xenial"
sudo: true

install:
  - pip install -r requirements.txt
  - pip install -r req_tests.txt
  - pip install -r req_docs.txt

script:
  - py.test --cov
  - make html

after_success:
  - coveralls
  - codecov
